version: '3'

volumes:
  data: {}

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aluxion
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  mock-smtp:
    container_name: mock-smtp
    image: mock-smtp
    build:
      context: ./mock/smtp
      dockerfile: Dockerfile
    env_file:
      - ./mock/smtp/local.env
    ports:
      - "8092:1080"
      - "1025:1025"
